name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

      - name: Shorten commit id
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: dockerashishshah76/python-app:${{ env.COMMIT_ID }}
    outputs:
      commit_id: ${{ env.COMMIT_ID }}
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
       - uses actions/checkout/@v3
         
       - name: Modify Values yaml
         shell: bash
         run: |
          echo '${{needs.ci.outputs.commit_id}}'
          pip install yq
          yq -Yi '.image.tag = "${{needs.ci.outputs.commit_id}}"' charts/python-app/values.yaml

       - name: Commit Changes 
         uses: EndBug/add-and-commit@v9
         with: 
          message: "values.yaml updated with the new commit Id ${{needs.ci.outputs.commit_id}}" 


       - name: Install Argocd
         shell: bash
         run: |
          VERSION=$(curl -L -s https://raw.githubusercontent.com/argoproj/argo-cd/stable/VERSION)
          curl -ksSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/download/v$VERSION/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64    

       - name: Argocd App Sync
         shell: bash
         run: |
          argocd login argocd-server.argocd  \
          --insecure --grpc-web \
          --username admin \
          --password ${{ secrets.ARGOCD_PASSWORD }} 
          argocd app sync python-app